### ISSUE TITLE
Links for deleted comments aren't showing up

### ISSUE THREAD

**Issue by 77vjdplu1N2h** [DenverCoder1/unedit-for-reddit#52] opened 2022-09-07 00:19 UTC
It seems like deleted comments aren't showing up on old Reddit.

Here's one example for a deleted comment that still appears in the comment tree:

https://www.reddit.com/r/AskReddit/comments/x7ebbc/what_are_the_most_overused_redundant_and_annoying/inca20j/

The comment is in pushshift here: https://api.pushshift.io/reddit/comment/search/?ids=inca20j

Here's an example that doesn't appear in the comment tree:

https://www.reddit.com/r/MadeMeSmile/comments/x6u4uc/this_is_the_way/inb58qc/

The comment is in pushshift here: https://api.pushshift.io/reddit/comment/search/?ids=inb58qc

(Even though the comment isn't rendered at all on old reddit, it looks like the HTML has some references to the comment ID or perhaps the user script could get the comment ID from the URL.)

It seems to be the same for mod removed comments:

https://www.reddit.com/r/meirl/comments/x4s0y0/meirl/imyku1h/

It's in pushshift here: https://api.pushshift.io/reddit/comment/search/?ids=imyku1h

---

Also want to say this is a great script! Thanks for writing and maintaining it.

**Comment by DenverCoder1** [comment] 2022-09-07 00:32
> Here's one example for a deleted comment that still appears in the comment tree:
> 
> [reddit.com/r/AskReddit/comments/x7ebbc/what_are_the_most_overused_redundant_and_annoying/inca20j](https://www.reddit.com/r/AskReddit/comments/x7ebbc/what_are_the_most_overused_redundant_and_annoying/inca20j/)

This one works for me on Reddit Redesign and Old Reddit, not sure why it wouldn't work for you. Which browser/version are you using?

> Here's an example that doesn't appear in the comment tree:
> 
> [reddit.com/r/MadeMeSmile/comments/x6u4uc/this_is_the_way/inb58qc](https://www.reddit.com/r/MadeMeSmile/comments/x6u4uc/this_is_the_way/inb58qc/)

I hadn't considered comments that don't appear through browsing, as I'm not sure how you'd ever find it on the page. It shouldn't be too difficult to add a link to those "there doesn't seem to be anything here" pages though. It seems to me like it would need to use the URL.

**Comment by 77vjdplu1N2h** [comment] 2022-09-07 01:14
> This one works for me on Reddit Redesign and Old Reddit, not sure why it wouldn't work for you. Which browser/version are you using?

I'm using Firefox 104. I've gotten that comment to work once or twice after opening it a bunch of times, but the link from the unedit user script almost never shows up. It might be some sort of conflict with the Reddit Enhancement Suite extension or the Reddit Moderator Toolbox extension which I am also running. If I disable those, that comment seems to work more consistently. I'm not a mod on any of these subreddits if that matters.

> I hadn't considered comments that don't appear through browsing, as I'm not sure how you'd ever find it on the page.

It usually happens when I'm trying to read a comment that was linked somewhere else.

**Comment by DenverCoder1** [comment] 2022-09-07 01:20
> I'm using Firefox 104. I've gotten that comment to work once or twice after opening it a bunch of times, but the link from the unedit user script almost never shows up. It might be some sort of conflict with the Reddit Enhancement Suite extension or the Reddit Moderator Toolbox extension which I am also running. If I disable those, that comment seems to work more consistently. I'm not a mod on any of these subreddits if that matters.

What version of the script? It works every time for me in Chrome, Brave (with RES), and Firefox.

**Comment by 77vjdplu1N2h** [comment] 2022-09-07 02:26
I'm using version 3.14.0.

**Comment by DenverCoder1** [comment] 2022-09-07 16:09
I can't seem to reproduce the issue no matter what I do. I'm going to close this as a feature request for comments not found in the comment tree, but you can open a new issue about the first deleted comment not working. Might need to include more details, possibly a screenshot. If I can't reproduce the issue, I won't be able to test any fixes.

**Closed** 2022-09-07 16:21 UTC
Labels: enhancement

**Comment by DenverCoder1** [comment] 2022-09-07 17:57
I think #57 might fix the issue. I was noticing some other small issues in Firefox that were fixed by this. I'll push an update for 3.15.0 soon.
